## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

format = "$directory$character$all"
right_format = """$git_branch$git_status$cmd_duration"""

# Disable the blank line at the start of the prompt
add_newline = true

[line_break]
disabled = true

[character]
format = "[](fg:#c4a7e7 bg:#26233a)[ ](fg:#26233a bg:#c4a7e7)[](fg:#c4a7e7 bg:none) $symbol "
success_symbol = "[](#89b4fa bold)"
error_symbol = "[](#c4a7e7 bold)"
vicmd_symbol = " "

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[cmd_duration]
min_time = 1
format = "[](fg:#26233a bg:none)[$duration]($style)[](fg:#26233a bg:#26233a)[](fg:#c4a7e7 bg:#26233a)[ ](fg:#26233a bg:#c4a7e7)[](fg:#c4a7e7 bg:none) "
disabled = false
style = "fg:#cdd6f4 bg:#26233a"

[directory]
format = "[](fg:#26233a bg:none)[$path ](fg:#cdd6f4 bg:#26233a)"
style = "fg:#26233a bg:#c4a7e7"
truncation_length = 3
truncate_to_repo=false
home_symbol = "~"
read_only = " "

[battery]
disabled = true

[git_branch]
format = "[](fg:#26233a bg:none)[$branch]($style)[](fg:#26233a bg:#26233a)[](fg:#c4a7e7 bg:#26233a)[](fg:#313244 bg:#c4a7e7)[](fg:#c4a7e7 bg:none) "
style = "fg:#cdd6f4 bg:#26233a"
symbol = " "

[git_status]
format="[](fg:#26233a bg:none)[$all_status$ahead_behind]($style)[](fg:#26233a bg:#26233a)[](fg:#c4a7e7 bg:#26233a)[ ](fg:#26233a bg:#c4a7e7)[](fg:#c4a7e7 bg:none) "
style = "fg:#cdd6f4 bg:#26233a"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "#a6e3a1"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"#f9e2af"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "
